CREATE DATABASE IF NOT EXISTS arl_db;

CREATE USER IF NOT EXISTS 'root'@'localhost' identified by 'root';
GRANT ALL PRIVILEGES ON arl_db.* TO 'root'@'localhost';
FLUSH PRIVILEGES;

USE arl_db;

CREATE TABLE books(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
author VARCHAR(255) NOT NULL,
category VARCHAR(255) NOT NULL,
description TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
